name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.3.0.app

    - name: Build
      run: xcodebuild -scheme test-cicd -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build

    - name: Run tests
      run: xcodebuild -scheme test-cicd -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' test
